export const ChatLanguages = [
    "Albanian", "Georgian", "Moldovan",
    "Arabic", "German", "Mongolian",
    "Armenian", "Greek", "Montenegrin",
    "Awadhi", "Gujarati", "Nepali",
    "Azerbaijani", "Haryanvi", "Norwegian",
    "Bashkir", "Hindi", "Oriya",
    "Basque", "Hungarian", "Pashto",
    "Belarusian", "Indonesian", "Persian (Farsi)",
    "Bengali", "Irish", "Polish",
    "Bhojpuri", "Italian", "Portuguese",
    "Bosnian", "Japanese", "Punjabi",
    "Brazilian Portuguese", "Javanese", "Rajasthani",
    "Bulgarian", "Kannada", "Romanian",
    "Cantonese (Yue)", "Kashmiri", "Russian",
    "Catalan", "Kazakh", "Sanskrit",
    "Chhattisgarhi", "Konkani", "Santali",
    "Chinese", "Korean", "Serbian",
    "Croatian", "Kyrgyz", "Sindhi",
    "Czech", "Latvian", "Sinhala",
    "Danish", "Lithuanian", "Slovak",
    "Dogri", "Macedonian", "Slovene",
    "Dutch", "Maithili", "Slovenian",
    "English", "Malay", "Ukrainian",
    "Estonian", "Maltese", "Urdu",
    "Faroese", "Mandarin Chinese", "Uzbek",
    "Finnish", "Marathi", "Vietnamese",
    "French", "Marwari", "Welsh",
    "Galician", "Min Nan", "Wu"
  ];

export const elevenlabsVoiceLanguages = [
    "English", "Japanese", "Chinese", "German", "Hindi",
    "French", "Korean", "Portuguese", "Italian", "Spanish",
    "Indonesian", "Dutch", "Turkish", "Filipino", "Polish",
    "Swedish", "Bulgarian", "Romanian", "Arabic", "Czech",
    "Greek", "Finnish", "Croatian", "Malay", "Slovak",
    "Danish", "Tamil", "Ukrainian", "Russian", "Hungarian",
    "Norwegian", "Vietnamese"
  ];
