export const ChatLanguages = [
  "Albanian",
  "Georgian",
  "Moldovan",
  "Arabic",
  "German",
  "Mongolian",
  "Armenian",
  "Greek",
  "Montenegrin",
  "Awadhi",
  "Gujarati",
  "Nepali",
  "Azerbaijani",
  "Haryanvi",
  "Norwegian",
  "Bashkir",
  "Hindi",
  "Oriya",
  "Basque",
  "Hungarian",
  "Pashto",
  "Belarusian",
  "Indonesian",
  "Persian (Farsi)",
  "Bengali",
  "Irish",
  "Polish",
  "Bhojpuri",
  "Italian",
  "Portuguese",
  "Bosnian",
  "Japanese",
  "Punjabi",
  "Brazilian Portuguese",
  "Javanese",
  "Rajasthani",
  "Bulgarian",
  "Kannada",
  "Romanian",
  "Cantonese (Yue)",
  "Kashmiri",
  "Russian",
  "Catalan",
  "Kazakh",
  "Sanskrit",
  "Chhattisgarhi",
  "Konkani",
  "Santali",
  "Chinese",
  "Korean",
  "Serbian",
  "Croatian",
  "Kyrgyz",
  "Sindhi",
  "Czech",
  "Latvian",
  "Sinhala",
  "Danish",
  "Lithuanian",
  "Slovak",
  "Dogri",
  "Macedonian",
  "Slovene",
  "Dutch",
  "Maithili",
  "Slovenian",
  "English",
  "Malay",
  "Ukrainian",
  "Estonian",
  "Maltese",
  "Urdu",
  "Faroese",
  "Mandarin Chinese",
  "Uzbek",
  "Finnish",
  "Marathi",
  "Vietnamese",
  "French",
  "Marwari",
  "Welsh",
  "Galician",
  "Min Nan",
  "Wu",
];

export const elevenlabsVoiceLanguages = [
  "English",
  "Japanese",
  "Chinese",
  "German",
  "Hindi",
  "French",
  "Korean",
  "Portuguese",
  "Italian",
  "Spanish",
  "Indonesian",
  "Dutch",
  "Turkish",
  "Filipino",
  "Polish",
  "Swedish",
  "Bulgarian",
  "Romanian",
  "Arabic",
  "Czech",
  "Greek",
  "Finnish",
  "Croatian",
  "Malay",
  "Slovak",
  "Danish",
  "Tamil",
  "Ukrainian",
  "Russian",
  "Hungarian",
  "Norwegian",
  "Vietnamese",
];

export const voices = [
  {
    id: 1,
    provider: "elevenlabs",
    details: {
      id: "9BWtsMINqrJLrRacOk9x",
      name: "Aria",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "female",
        use_case: "social media",
        description: "expressive",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/9BWtsMINqrJLrRacOk9x/405766b8-1f4e-4d3c-aba1-6f25333823ec.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.444675",
    updated_at: "2025-02-25T07:27:44.444675",
  },
  {
    id: 2,
    provider: "elevenlabs",
    details: {
      id: "CwhRBWXzGAHq8TQ4Fs17",
      name: "Roger",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "male",
        use_case: "social media",
        description: "confident",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/CwhRBWXzGAHq8TQ4Fs17/58ee3ff5-f6f2-4628-93b8-e38eb31806b0.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 3,
    provider: "elevenlabs",
    details: {
      id: "EXAVITQu4vr4xnSDxMaL",
      name: "Sarah",
      labels: {
        age: "young",
        accent: "american",
        gender: "female",
        use_case: "news",
        description: "soft",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/01a3e33c-6e99-4ee7-8543-ff2216a32186.mp3",
      high_quality_base_model_ids: [
        "eleven_turbo_v2",
        "eleven_multilingual_v2",
        "eleven_turbo_v2_5",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 4,
    provider: "elevenlabs",
    details: {
      id: "FGY2WhTYpPnrIDTdsKH5",
      name: "Laura",
      labels: {
        age: "young",
        accent: "American",
        gender: "female",
        use_case: "social media",
        description: "upbeat",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/FGY2WhTYpPnrIDTdsKH5/67341759-ad08-41a5-be6e-de12fe448618.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 5,
    provider: "elevenlabs",
    details: {
      id: "IKne3meq5aSn9XLyUdCD",
      name: "Charlie",
      labels: {
        age: "middle aged",
        accent: "Australian",
        gender: "male",
        use_case: "conversational",
        description: "natural",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/IKne3meq5aSn9XLyUdCD/102de6f2-22ed-43e0-a1f1-111fa75c5481.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_multilingual_v1",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 6,
    provider: "elevenlabs",
    details: {
      id: "JBFqnCBsd6RMkjVDRZzb",
      name: "George",
      labels: {
        age: "middle aged",
        accent: "British",
        gender: "male",
        use_case: "narration",
        description: "warm",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/JBFqnCBsd6RMkjVDRZzb/e6206d1a-0721-4787-aafb-06a6e705cac5.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 7,
    provider: "elevenlabs",
    details: {
      id: "N2lVS1w4EtoT3dr4eOWO",
      name: "Callum",
      labels: {
        age: "middle-aged",
        accent: "Transatlantic",
        gender: "male",
        use_case: "characters",
        description: "intense",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/N2lVS1w4EtoT3dr4eOWO/ac833bd8-ffda-4938-9ebc-b0f99ca25481.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_multilingual_v1",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 8,
    provider: "elevenlabs",
    details: {
      id: "SAz9YHcvj6GT2YYXdXww",
      name: "River",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "non-binary",
        use_case: "social media",
        description: "confident",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/SAz9YHcvj6GT2YYXdXww/e6c95f0b-2227-491a-b3d7-2249240decb7.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_sts_v2",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 9,
    provider: "elevenlabs",
    details: {
      id: "TX3LPaxmHKxFdv7VOQHJ",
      name: "Liam",
      labels: {
        age: "young",
        accent: "American",
        gender: "male",
        use_case: "narration",
        description: "articulate",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/TX3LPaxmHKxFdv7VOQHJ/63148076-6363-42db-aea8-31424308b92c.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_multilingual_v1",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 10,
    provider: "elevenlabs",
    details: {
      id: "XB0fDUnXU5powFXDhCwa",
      name: "Charlotte",
      labels: {
        age: "young",
        accent: "Swedish",
        gender: "female",
        use_case: "characters",
        description: "seductive",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/XB0fDUnXU5powFXDhCwa/942356dc-f10d-4d89-bda5-4f8505ee038b.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_multilingual_v1",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 11,
    provider: "elevenlabs",
    details: {
      id: "Xb7hH8MSUJpSbSDYk0k2",
      name: "Alice",
      labels: {
        age: "middle-aged",
        accent: "British",
        gender: "female",
        use_case: "news",
        description: "confident",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/Xb7hH8MSUJpSbSDYk0k2/d10f7534-11f6-41fe-a012-2de1e482d336.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 12,
    provider: "elevenlabs",
    details: {
      id: "XrExE9yKIg1WjnnlVkGX",
      name: "Matilda",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "female",
        use_case: "narration",
        description: "friendly",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/XrExE9yKIg1WjnnlVkGX/b930e18d-6b4d-466e-bab2-0ae97c6d8535.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_multilingual_v1",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 13,
    provider: "elevenlabs",
    details: {
      id: "bIHbv24MWmeRgasZH58o",
      name: "Will",
      labels: {
        age: "young",
        accent: "American",
        gender: "male",
        use_case: "social media",
        description: "friendly",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/bIHbv24MWmeRgasZH58o/8caf8f3d-ad29-4980-af41-53f20c72d7a4.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 14,
    provider: "elevenlabs",
    details: {
      id: "cgSgspJ2msm6clMCkdW9",
      name: "Jessica",
      labels: {
        age: "young",
        accent: "American",
        gender: "female",
        use_case: "conversational",
        description: "expressive",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11683d45a.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 15,
    provider: "elevenlabs",
    details: {
      id: "cjVigY5qzO86Huf0OWal",
      name: "Eric",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "male",
        use_case: "conversational",
        description: "friendly",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/cjVigY5qzO86Huf0OWal/d098fda0-6456-4030-b3d8-63aa048c9070.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 16,
    provider: "elevenlabs",
    details: {
      id: "iP95p4xoKVk53GoZ742B",
      name: "Chris",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "male",
        use_case: "conversational",
        description: "casual",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/iP95p4xoKVk53GoZ742B/3f4bde72-cc48-40dd-829f-57fbf906f4d7.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 17,
    provider: "elevenlabs",
    details: {
      id: "nPczCjzI2devNBz1zQrb",
      name: "Brian",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "male",
        use_case: "narration",
        description: "deep",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/nPczCjzI2devNBz1zQrb/2dd3e72c-4fd3-42f1-93ea-abc5d4e5aa1d.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 18,
    provider: "elevenlabs",
    details: {
      id: "onwK4e9ZLuTAKqWW03F9",
      name: "Daniel",
      labels: {
        age: "middle-aged",
        accent: "British",
        gender: "male",
        use_case: "news",
        description: "authoritative",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/onwK4e9ZLuTAKqWW03F9/7eee0236-1a72-4b86-b303-5dcadc007ba9.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_multilingual_v1",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 19,
    provider: "elevenlabs",
    details: {
      id: "pFZP5JQG7iQjIQuC4Bku",
      name: "Lily",
      labels: {
        age: "middle-aged",
        accent: "British",
        gender: "female",
        use_case: "narration",
        description: "warm",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 20,
    provider: "elevenlabs",
    details: {
      id: "pqHfZKP75CvOlQylNhV4",
      name: "Bill",
      labels: {
        age: "old",
        accent: "American",
        gender: "male",
        use_case: "narration",
        description: "trustworthy",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/premade/voices/pqHfZKP75CvOlQylNhV4/d782b3ff-84ba-4029-848c-acf01285524d.mp3",
      high_quality_base_model_ids: [
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_turbo_v2_5",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
        "eleven_turbo_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 21,
    provider: "elevenlabs",
    details: {
      id: "L0Dsvb3SLTyegXwtm47J",
      name: "Archer",
      labels: {
        age: "middle_aged",
        accent: "british",
        gender: "male",
        language: "en",
        use_case: "conversational",
        descriptive: "calm",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/custom/voices/L0Dsvb3SLTyegXwtm47J/EKoXN08bacukhTjtp6sq.mp3",
      high_quality_base_model_ids: [
        "eleven_turbo_v2",
        "eleven_multilingual_v2",
        "eleven_v2_flash",
        "eleven_flash_v2",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 22,
    provider: "elevenlabs",
    details: {
      id: "UgBBYS2sOqTuMpoF3BR0",
      name: "Mark - Natural Conversations",
      labels: {
        age: "young",
        accent: "american",
        gender: "male",
        language: "en",
        use_case: "conversational",
        descriptive: "casual",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/database/user/y7Wmp2r8nCeGkLiXiwMOVWktro13/voices/UgBBYS2sOqTuMpoF3BR0/0Oc7jiXwWN9kRTXfQsmw.mp3",
      high_quality_base_model_ids: [
        "eleven_multilingual_v2",
        "eleven_turbo_v2_5",
        "eleven_turbo_v2",
        "eleven_multilingual_sts_v2",
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_flash_v2_5",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 23,
    provider: "elevenlabs",
    details: {
      id: "aCChyB4P5WEomwRsOKRh",
      name: "Salma - Conversational Expressive Voice",
      labels: {
        age: "young",
        accent: "arabic",
        gender: "female",
        language: "en",
        use_case: "conversational",
        descriptive: "pleasant",
      },
      preview_url:
        "https://storage.googleapis.com/eleven-public-prod/database/user/TLzQBQZ61wQrytFwliQpe4LeshE3/voices/aCChyB4P5WEomwRsOKRh/pwNKTCc35h8TdZeZNkAR.mp3",
      high_quality_base_model_ids: [
        "eleven_turbo_v2_5",
        "eleven_v2_flash",
        "eleven_flash_v2",
        "eleven_multilingual_sts_v2",
        "eleven_turbo_v2",
        "eleven_multilingual_v2",
        "eleven_v2_5_flash",
        "eleven_flash_v2_5",
      ],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 24,
    provider: "openai",
    details: {
      id: "alloy",
      name: "Alloy",
      labels: {
        age: "young",
        accent: "American",
        gender: "neutral",
        use_case: "general",
        description: "balanced",
      },
      preview_url: "https://convoai-voices.s3.ap-south-1.amazonaws.com/alloy.mp3",
      high_quality_base_model_ids: ["tts-1"],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 25,
    provider: "openai",
    details: {
      id: "ash",
      name: "ash",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "neutral",
        use_case: "general",
        description: "clear",
      },
      preview_url: "https://convoai-voices.s3.ap-south-1.amazonaws.com/Ash.mp3",
      high_quality_base_model_ids: ["tts-1"],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 26,
    provider: "openai",
    details: {
      id: "coral",
      name: "coral",
      labels: {
        age: "young",
        accent: "American",
        gender: "neutral",
        use_case: "general",
        description: "expressive",
      },
      preview_url: "https://convoai-voices.s3.ap-south-1.amazonaws.com/coral.mp3",
      high_quality_base_model_ids: ["tts-1"],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
  {
    id: 27,
    provider: "openai",
    details: {
      id: "sage",
      name: "sage",
      labels: {
        age: "middle-aged",
        accent: "American",
        gender: "neutral",
        use_case: "general",
        description: "professional",
      },
      preview_url: "https://convoai-voices.s3.ap-south-1.amazonaws.com/sage.mp3",
      high_quality_base_model_ids: ["tts-1"],
    },
    created_at: "2025-02-25T07:27:44.445648",
    updated_at: "2025-02-25T07:27:44.445648",
  },
];


export const GPT_MODELS = [
  {
    value: "gpt-4",
    label: "GPT-4",
  },
  {
    value: "gpt-4o",
    label: "GPT-4O",
  },
  {
    value: "gpt-4o-20240513",
    label: "GPT-4O (2024-05-13)",
  },
  {
    value: "gpt-4o-mini",
    label: "GPT-4O Mini",
  },
  {
    value: "gpt-4o-mini-20240718",
    label: "GPT-4O Mini (2024-07-18)",
  },
  {
    value: "gpt-4-turbo",
    label: "GPT-4 Turbo",
  },
  {
    value: "gpt-4-turbo-20240409",
    label: "GPT-4 Turbo (2024-04-09)",
  },
  {
    value: "gpt-4-turbo-preview",
    label: "GPT-4 Turbo Preview",
  },
  {
    value: "gpt-40125-preview",
    label: "GPT-4 (0125 Preview)",
  },
  {
    value: "gpt-41106-preview",
    label: "GPT-4 (1106 Preview)",
  },
  {
    value: "gpt-4-vision-preview",
    label: "GPT-4 Vision Preview",
  },
  {
    value: "gpt-41106-vision-preview",
    label: "GPT-4 (1106 Vision Preview)",
  },
  {
    value: "gpt-40314",
    label: "GPT-4 (0314)",
  },
  {
    value: "gpt-40613",
    label: "GPT-4 (0613)",
  },
  {
    value: "gpt-432k",
    label: "GPT-4 32K",
  },
  {
    value: "gpt-432k-0314",
    label: "GPT-4 32K (0314)",
  },
  {
    value: "gpt-432k-0613",
    label: "GPT-4 32K (0613)",
  },
  {
    value: "gpt-3.5-turbo",
    label: "GPT-3.5 Turbo",
  },
  {
    value: "gpt-3.5-turbo-16k",
    label: "GPT-3.5 Turbo 16K",
  },
  {
    value: "gpt-3.5-turbo-0301",
    label: "GPT-3.5 Turbo (0301)",
  },
  {
    value: "gpt-3.5-turbo-0613",
    label: "GPT-3.5 Turbo (0613)",
  },
  {
    value: "gpt-3.5-turbo-1106",
    label: "GPT-3.5 Turbo (1106)",
  },
  {
    value: "gpt-3.5-turbo-16k-0613",
    label: "GPT-3.5 Turbo 16K (0613)",
  }
];

